<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-02T16:43:50 IST" name="Default suite" finished-at="2024-02-02T16:43:50 IST" duration-ms="374">
    <groups>
    </groups>
    <test started-at="2024-02-02T16:43:50 IST" name="Default test" finished-at="2024-02-02T16:43:50 IST" duration-ms="374">
      <class name="com.selenium.TestNg.Testing">
        <test-method signature="testthree()[pri:-1, instance:com.selenium.TestNg.Testing@202b0582]" started-at="2024-02-02T16:43:50 IST" name="testthree" finished-at="2024-02-02T16:43:50 IST" duration-ms="30" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testthree -->
        <test-method signature="testone()[pri:0, instance:com.selenium.TestNg.Testing@202b0582]" started-at="2024-02-02T16:43:50 IST" name="testone" finished-at="2024-02-02T16:43:50 IST" duration-ms="8" status="FAIL">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method Testing.testone()[pri:0, instance:com.selenium.TestNg.Testing@202b0582] should have thrown an exception of type class java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method Testing.testone()[pri:0, instance:com.selenium.TestNg.Testing@202b0582] should have thrown an exception of type class java.lang.NullPointerException
at org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)
at org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:860)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:718)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testone -->
        <test-method signature="testtwo()[pri:0, instance:com.selenium.TestNg.Testing@202b0582]" started-at="2024-02-02T16:43:50 IST" name="testtwo" finished-at="2024-02-02T16:43:50 IST" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testtwo -->
        <test-method signature="testfour()[pri:1, instance:com.selenium.TestNg.Testing@202b0582]" started-at="2024-02-02T16:43:50 IST" name="testfour" finished-at="2024-02-02T16:43:50 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testfour -->
      </class> <!-- com.selenium.TestNg.Testing -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
