<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="50" started-at="2023-07-09T08:07:31Z" finished-at="2023-07-09T08:07:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="50" started-at="2023-07-09T08:07:31Z" finished-at="2023-07-09T08:07:31Z">
      <class name="com.selenium.TestNg.HardandSoftAssertions">
        <test-method status="FAIL" signature="HardAssertion()[pri:0, instance:com.selenium.TestNg.HardandSoftAssertions@5d624da6]" name="HardAssertion" duration-ms="16" started-at="2023-07-09T13:37:31Z" finished-at="2023-07-09T13:37:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [babu] but found [seshu]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [babu] but found [seshu]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.selenium.TestNg.HardandSoftAssertions.HardAssertion(HardandSoftAssertions.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HardAssertion -->
        <test-method status="PASS" signature="SoftAssertion()[pri:0, instance:com.selenium.TestNg.HardandSoftAssertions@5d624da6]" name="SoftAssertion" duration-ms="6" started-at="2023-07-09T13:37:31Z" finished-at="2023-07-09T13:37:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SoftAssertion -->
      </class> <!-- com.selenium.TestNg.HardandSoftAssertions -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
